### ISSUE TITLE
css的弹性布局 | OneBoluo

### ISSUE THREAD

**Issue by JavanShen** [JavanShen/JavanShen.github.io#6]
https://javanshen.github.io/2020/04/18/%E5%BC%B9%E6%80%A7%E5%B8%83%E5%B1%80/ 

 记录前端笔记

**Comment by JavanShen** [comment]
沙发

**Comment by WoodFY** [comment]
签名太JB中二了

**Comment by JavanShen** [comment]
> @IVVIMU
> 签名太JB中二了

![表情包](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScyq3rpdgu56hHIzG1R5AAYMty-OMOBOB2U9sFyZlBXRkkaLLn&usqp=CAU)
